FROM python:3.10

WORKDIR /app

# Install system dependencies, including compilers
# Add this before pip install
RUN apt-get update && \
    apt-get install -y wget build-essential libsqlite3-dev && \
    wget https://www.sqlite.org/2023/sqlite-autoconf-3410200.tar.gz && \
    tar xzf sqlite-autoconf-3410200.tar.gz && \
    cd sqlite-autoconf-3410200 && \
    ./configure && make && make install && \
    ldconfig && \
    cd .. && rm -rf sqlite-autoconf-3410200*


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
