FROM python:3.13-slim

WORKDIR /app

# Install system dependencies, including compilers
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    clang \
    sqlite3 \
    libsqlite3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
